apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./operatorgroup.yaml
  - ./subscription.yaml
  - ./console-plugin.yaml
  - ./rook-operator-config.yaml
  - ./odf-master-patcher.yaml
patches:
  - target:
      group: operator.openshift.io
      kind: Console
      name: cluster
    patch: |-
      - op: add
        path: /spec/plugins/-
        value: odf-console
  - target:
      kind: Deployment
      namespace: openshift-storage
    patch: |-
      - op: add
        path: /spec/template/spec/tolerations
        value:
          - key: node-role.kubernetes.io/master
            operator: Exists
            effect: NoSchedule
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
            effect: NoSchedule
  - target:
      kind: StatefulSet
      namespace: openshift-storage
    patch: |-
      - op: add
        path: /spec/template/spec/tolerations
        value:
          - key: node-role.kubernetes.io/master
            operator: Exists
            effect: NoSchedule
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
            effect: NoSchedule