apiVersion: v1
kind: Namespace
metadata:
  name: openshift-storage
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    # scheduler.alpha.kubernetes.io/defaultNodeSelector: node-role.kubernetes.io/control-plane=
    openshift.io/node-selector: "node-role.kubernetes.io/master="
