apiVersion: v1
kind: Namespace
metadata:
  name: openshift-storage
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    # openshift.io/node-selector: "node-role.kubernetes.io/control-plane="
    # scheduler.alpha.kubernetes.io/defaultTolerations: '[{"key": "node-role.kubernetes.io/control-plane", "operator": "Exists", "effect": "NoSchedule"}]'