---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/ha
  # - ../../components/tls
namespace: vault
labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false
    includeTemplates: false
patches:
  # Set the external hostname for your Vault instance
  - target:
      kind: Route
      name: vault
    patch: |
      apiVersion: route.openshift.io/v1
      kind: Route
      metadata:
        name: vault
      spec:
        host: "vault.darkloft.homelab"
  # Set the internal route hostname
  - target:
      kind: Route
      name: vault-internal
    patch: |
      apiVersion: route.openshift.io/v1
      kind: Route
      metadata:
        name: vault-internal
      spec:
        host: "vault-internal.darkloft.homelab"
  # Override the Vault image to a specific version
  - target:
      kind: StatefulSet
      name: vault
    patch: |
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: vault
      spec:
        template:
          spec:
            containers:
              - name: vault
                image: "registry.connect.redhat.com/hashicorp/vault:1.15"
                imagePullPolicy: IfNotPresent