apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  name: ocs-storagecluster
  namespace: openshift-storage
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  monDataDirHostPath: /var/lib/rook
  resourceProfile: lean
  placement:
    # --- PIN CRITICAL CORE TO MASTER NODES ---
    rgw:
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: node-role.kubernetes.io/control-plane
                  operator: Exists
            - matchExpressions:
                - key: node-role.kubernetes.io/master
                  operator: Exists
    noobaa:
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: node-role.kubernetes.io/control-plane
                  operator: Exists
    # --- OFFLOAD AUXILIARY INFRASTRUCTURE TO STANDARD WORKERS ---
    # all:
    #   nodeAffinity:
    #     requiredDuringSchedulingIgnoredDuringExecution:
    #       nodeSelectorTerms:
    #         - matchExpressions:
    #             - key: node-role.kubernetes.io/worker
    #               operator: Exists
  storageDeviceSets:
    - name: ocs-deviceset
      count: 1          
      replica: 3        
      resources:
        limits:
          cpu: "2"
          memory: "8Gi"
        requests:
          cpu: "1"
          memory: "4Gi"
      placement:
        tolerations:
          - key: node-role.kubernetes.io/master
            operator: Exists
            effect: NoSchedule
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
            effect: NoSchedule
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/master
                    operator: Exists
      dataPVCTemplate:
        spec:
          storageClassName: local-block
          accessModes:
            - ReadWriteOnce
          volumeMode: Block
          resources:
            requests:
              storage: 1863Gi