apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components: []
resources:
  - ./local-storage-operator.yaml
  - ./openshift-data-foundation.yaml
  - ./openshift-gitops.yaml
  - ./vault.yaml
patches: []
