apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources: []
patches:
  # --- CRITICAL CORE (Pinned to Masters) ---
  - path: storage-core-workloads.yaml
    target:
      namespace: openshift-storage
      kind: Deployment
      labelSelector: "app=rook-ceph-rgw"
  # --- AUXILIARY INFRASTRUCTURE (Offloaded to Workers) ---
  - path: ./storage-aux-workloads.yaml
    target:
      namespace: openshift-storage
      kind: Deployment
      labelSelector: "app=ocs-metrics-exporter"
  - path: ./storage-aux-workloads.yaml
    target:
      namespace: openshift-storage
      kind: Deployment
      labelSelector: "app=odf-blackbox-exporter"
  - path: ./storage-aux-workloads.yaml
    target:
      namespace: openshift-storage
      kind: Deployment
      labelSelector: "app=ocs-provider-server"
  - path: ./ceph-priority-patch.yaml
    target:
      group: ceph.rook.io
      version: v1
      kind: CephFilesystem
      name: ocs-storagecluster-cephfilesystem
      namespace: openshift-storage
  - path: ./noobaa-infra-patch.yaml
    target:
      group: noobaa.io
      version: v1alpha1
      kind: NooBaa
      name: noobaa
      namespace: openshift-storage
