apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-aux-workloads
  namespace: openshift-storage
spec:
  template:
    spec:
      tolerations: []
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/worker
                    operator: Exists