apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./operatorgroup.yaml
  - ./localvolumedevicelinks.yaml
  - ./localvolumediscoveries.yaml
  - ./localvolumediscoveryresults.yaml
  - ./localvolumes.yaml
  - ./localvolumesets.yaml
  - ./installplan-job.yaml
  - ./prometheus-role-binding.yaml
  - ./prometheus-role.yaml
  - ./subscription.yaml