apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: argocd
  namespace: openshift-gitops
spec:
  # Default ArgoCD configuration
  server:
    route:
      enabled: false
  resourceOverride:
    apiVersions:
    - v1
    - apps/v1
    - batch/v1
  config:
    dashboard:
      readonly: false