apiVersion: console.openshift.io/v1
kind: ConsolePlugin
metadata:
  name: gitops-plugin
spec:
  displayName: "OpenShift GitOps"
  backend:
    type: Service
    service:
      name: gitops-plugin
      namespace: openshift-gitops
      port: 9001
      path: /