apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components: []
resources:
- ./namespace.yaml
- ./service-account.yaml
- ./rbac.yaml
# - ./argocd.yaml
- ./operatorgroup.yaml
patches:
  - target:
      kind: Deployment
      name: gitops-operator-controller-manager
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: ENABLE_CONSOLE_PLUGIN
          value: "true"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: CONSOLE_PLUGIN_PORT
          value: "8080"