apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
- ./subscription.yaml
- ./clusterserviceversion.yaml
patches:
- target:
    kind: ArgoCD
    name: argocd
  patch: |-
    - op: add
      path: /spec/server/route/enabled
      value: true