apiVersion: kustomize.config.k8s.io/v1beta1
kind: Component
resources: 
  - ./local-storage-operator-clusterserviceversion
  - ./localvolumedevicelinks
  - ./localvolumediscoveries
  - ./localvolumediscoveryresults
  - ./localvolumes
  - ./localvolumesets
  - ./prometheus-role-binding
  - ./prometheus-role