apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources: 
  - ./clusterserviceversion.yaml
  - ./localvolumedevicelinks.yaml
  - ./localvolumediscoveries.yaml
  - ./localvolumediscoveryresults.yaml
  - ./localvolumes.yaml
  - ./localvolumesets.yaml
  - ./prometheus-role-binding.yaml
  - ./prometheus-role.yaml