---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - statefulset.yaml
  - pdb.yaml
  # - vpa.yaml
  - probes.yaml
configMapGenerator:
  - name: vault-config
    namespace: vault
    files:
      - vault.hcl
